-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 10, 2017 at 09:38 AM
-- Server version: 5.7.19-0ubuntu0.16.04.1
-- PHP Version: 7.0.18-1+deb.sury.org~xenial+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sy_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id` int(11) NOT NULL,
  `title` char(50) NOT NULL,
  `tags` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `image` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id`, `title`, `tags`, `description`, `image`, `created_at`) VALUES
(1, 'Historical', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.', 'blog-inner-img.jpg', '2017-08-09 12:00:24'),
(2, 'Animation', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.', 'blog-inner-img.jpg', '2017-08-08 05:03:42'),
(3, 'Action', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.', 'blog-inner-img.jpg', '2017-08-08 05:04:42'),
(4, 'Trailer', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.', 'blog-inner-img.jpg', '2017-08-08 05:05:42'),
(5, 'Drama', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\r\n\r\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.', 'blog-inner-img.jpg', '2017-08-08 05:06:42'),
(6, 'Comedy', 'Design, Drawing, Photoshop, Premiere', 'Lorem ipsum dolor sit <b>amet</b>, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.<i> <u><b>Etiam eget facilisis orci.\n\nSometimes the simplest things are the hardest to find</b></u></i>.&nbsp;<div>So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find.&nbsp;</div><div><br></div><div>So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find.&nbsp;</div><div>So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\n\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at felis aliquam libero tempus iaculis in et nisi. Praesent a sem vel tellus dignissim convallis nec eget diam. Nullam sed ex aliquet, condimentum est et, posuere nisl. Aenean pretium vel tortor ac laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eget facilisis orci.\n\nSometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you. Sometimes the simplest things are the hardest to find. So we created a new line for everyday life, All Year Round. Sometimes the simplest things are the hardest to find you.</div>', 'blog-inner-img.jpg', '2017-08-09 15:13:01');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
